CREATE TABLE vaga(

    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA DATE NOT NULL,
    SALARIO FLOAT NOT NULL

 );

CREATE TABLE candidato(

    ID SERIAL PRIMARY KEY,
    RG VARCHAR(9),
    NOME_CANDIDATO VARCHAR(100),
    EMAIL VARCHAR(150)

);